use customer_behaviour;

SELECT * FROM customer;
SELECT COUNT(*) AS total_rows FROM customer;

ALTER TABLE customer 
RENAME COLUMN purchase_amount_(usd) TO purchase_amount;

-- Q1 What is the total revenue generated by Male VS Female Customrer 
SELECT gender , SUM(purchase_amount) AS total_revenue
FROM customer 
GROUP BY gender;

-- Q2 Which customer used a discount but still spent more then the avearagre puchase amount

SELECT customer_id , age , gender FROM customer 
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3 Which are the Top 5 products with the highest average review rating
SELECT item_purchased , ROUND(AVG(review_rating),2) 
FROM customer  
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4 Comapre the average Purchase Amount b/w Standard and Express Shippping 

SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5 Do Subscribed Customers Spend more ? Compare average spend and total 
-- revenue b/w subscribers and non sunscribers  

SELECT subscription_status , ROUND(AVG(purchase_amount),2) , SUM(purchase_amount) AS
total_revenue
FROM customer 
GROUP BY subscription_status;

-- Q6 Which 5 products have the highest percentage of purchases with discount applied
SELECT item_purchased , 
ROUND(SUM(CASE WHEN discount_applied = 'Yes'  THEN 1 ELSE 0 END)*100/COUNT(*),2) AS
discount_rate
FROM customer
GROUP BY  item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customers into New , Returning and Loyal based on their total number of 
-- previous purchases , and show the count of each segment . 

SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) t
GROUP BY customer_segment;

-- Q8 What are top 3 most purchased product within each category
SELECT category, item_purchased, total_purchases
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE rnk <= 3
ORDER BY category, total_purchases DESC;

-- Q9 Are custoers who are repeat buyers (more then 5 previous purchases) also likely to 
-- subscribe 
 SELECT subscription_status,
 COUNT(customer_id) 
 FROM customer 
 WHERE previous_purchases > 5
 GROUP BY subscription_status;
 
    
-- Q10 What is the revenue contribution of each age group ?
SELECT age_group , 
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
